### ISSUE TITLE
Run Data Node in a container

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/elastic-stream#112]

**Comment by lizhanhui** [comment]
io-uring by default is restricted in the container: https://github.com/moby/moby/issues/39396 
https://github.com/netty/netty-incubator-transport-io_uring/issues/41

Possibly need to update `libseccomp` to its latest version

**Comment by lizhanhui** [comment]
It turns out that the overlay filesystem offers limited support for io-uring. Once we provide a volume, say bind a host path via `-v /path/to/host:/path/to/container`. Then everything works as expected.

**Comment by lizhanhui** [comment]
Fixed
