### ISSUE TITLE
CRC32 does not use the pclmulqdq variant

### ISSUE THREAD

**Issue by lizhanhui** [AutoMQ/elastic-stream#192]
crc32fast has two variants: baseline and pclmulqdq.
According to the flamegraph collected, data-node uses baseline variant only. Need to investigate how to use the accelerated SIMD variant. 

https://dev.to/cloudx/building-optimized-binaries-with-rust-k8b may be helpful.

https://crates.io/crates/crc32fast

https://www.fastmail.com/blog/the-search-for-a-faster-crc32/

**Comment by Tianpingan** [comment]
maybe you can use these three macros in Rust to check if your CPU supports the features required by the "pclmulqdq variant".
```
is_x86_feature_detected!("pclmulqdq")
is_x86_feature_detected!("sse2")
is_x86_feature_detected!("sse4.1")
```

according to the source code of crc32fast, it uses these three macros in `Hasher::new()` to determine the State(**Baseline** or **Specialized**)

```rust
// lib.rs of crc32fast
	impl Hasher {
		pub fn new() -> Self {
			Self::new_with_initial(DEFAULT_INIT_STATE)
		}
		pub fn new_with_initial(init: u32) -> Self {
	        Self::new_with_initial_len(init, 0)
	    }
	    pub fn new_with_initial_len(init: u32, amount: u64) -> Self {
	        Self::internal_new_specialized(init, amount)
	            .unwrap_or_else(|| Self::internal_new_baseline(init, amount))
		    }
	    pub fn internal_new_specialized(init: u32, amount: u64) -> Option<Self> {
	        {
	            if let Some(state) = specialized::State::new(init) {
	                return Some(Hasher {
	                    amount,
	                    state: State::Specialized(state),
	                });
	            }
	        }
	        None
	    }
}

// pclmulqdq.rs of crc32fast
    pub fn new(state: u32) -> Option<Self> {
        if is_x86_feature_detected!("pclmulqdq")
            && is_x86_feature_detected!("sse2")
            && is_x86_feature_detected!("sse4.1")
        {
            // SAFETY: The conditions above ensure that all
            //         required instructions are supported by the CPU.
            Some(Self { state })
        } else {
            None
        }
    }
```

**Comment by lizhanhui** [comment]
<img width="919" alt="image" src="https://github.com/AutoMQ/elastic-stream/assets/641819/db27bc10-4004-4c3f-af3d-99e33d3cb1ac">

For aarch64, we forgot to enable nightly feature during perf test.
