### ISSUE TITLE
RefCell reference is held across an await point

### ISSUE THREAD

**Issue by Tianpingan** [AutoMQ/elastic-stream#218]
After introducing the metrics reporting feature, I found that  '**already borrowed: BorrowMutError**' error would often occur.

The reason is **RefCell reference is held across an await point**, alerted by the output of cargo clippy

`self.sessions.borrow()` from here(not only report_metrics, but aslo allocate_id, list_range, ...): 
```rust
    pub(crate) async fn allocate_id(
        &self,
        host: &str,
        timeout: Option<Duration>,
    ) -> Result<i32, ClientError> {
        if let Some((_, session)) = self.sessions.borrow().iter().next() {
           //...
            if let Err(e) = session.write(request, tx).await 
         }
}
    pub(crate) async fn list_range(
        &self,
        criteria: RangeCriteria,
    ) -> Result<Vec<RangeMetadata>, ClientError> {
        if let Some((_, session)) = self.sessions.borrow().iter().next() {
        //...    
        if let Err(_ctx) = session.write(request, tx).await 
        }
}
     pub(crate) async fn report_metrics()
.....
```

RefCell reference is held across an await point(`session.write(request, tx).await`), so when the `borrow_mut()` called by `heartbeat()`, error occured

`self.sessions.borrow_mut()` from here: 
```rust
    pub(crate) async fn heartbeat(&self) -> Result<(), ClientError> {
                    // Remove sessions that are no longer valid
                    self.sessions
                        .borrow_mut()
                        .drain_filter(|k, _v| !addrs.contains(k))
                        .for_each(|(k, _v)| {
                            self.endpoints.borrow_mut().drain_filter(|e| {
                                e == &k
                            });
                            info!("Session to {} will be disconnected because latest Placement Manager Cluster does not contain it any more", k);
                        });
```

**Comment by lizhanhui** [comment]
It's one of the known to-do items of client crate.  CompositeSession#append has the fix.

Another pending issue to resolve is that some RPC shall be routed to leader placement manager. For your case, metrics are supposed to broadcast to all PM nodes.

**Comment by lizhanhui** [comment]
https://github.com/AutoMQ/elastic-stream/pull/222 should have fixed this issue.
