### ISSUE TITLE
Placement Manager support idempotent create range 

### ISSUE THREAD

**Issue by superhx** [AutoMQ/elastic-stream#300]

**Comment by Chillax-0v0** [comment]
Currently, "Create the same range after creating it" will return an error and do nothing.
What does "idempotent" mean here?

**Comment by superhx** [comment]
> Currently, "Create the same range after creating it" will return an error and do nothing. What does "idempotent" mean here?

If create range timeout(but pm success), client will retry create the range with the same (range_index, start_offset, epoch), then PM should response success and return the replica nodes
