### ISSUE TITLE
Creating the range[range-index=0] should NOT require prerequisite seal

### ISSUE THREAD

**Issue by lizhanhui** [AutoMQ/elastic-stream#304]
components/client/src/composite_session.rs:636 2023-05-25T21:02:15 [TRACE] - Received placement manager cluster Some([PlacementManagerNode { name: "pm-iZj6c3bw7e7v29ygmfwj53Z", advertise_addr: "127.0.0.1:12378", leader: true }])
components/client/src/composite_session.rs:113 2023-05-25T21:02:15 [DEBUG] - Refresh placement manager cluster leadership
components/client/src/session.rs:273 2023-05-25T21:02:15 [INFO] - Node-state of 127.0.0.1:12378 is changed: Unknown --> Leader
components/client/src/client.rs:155 2023-05-25T21:02:15 [TRACE] - Create range replica to composite-channel=localhost:12378
components/client/src/composite_session.rs:224 2023-05-25T21:02:15 [TRACE] - State of session to 127.0.0.1:12378 is Leader
components/client/src/session.rs:181 2023-05-25T21:02:15 [TRACE] - Sending Request {
    timeout: 1s,
    headers: CreateRange {
        range: RangeMetadata {
            stream_id: 100,
            epoch: 0,
            index: 0,
            start: 0,
            end: None,
            replica: [],
            replica_count: 0,
            ack_count: 0,
        },
    },
} to 127.0.0.1:12378
components/transport/src/connection.rs:179 2023-05-25T21:02:15 [TRACE] - Get 92 bytes to write to: 127.0.0.1:12378
components/transport/src/connection.rs:190 2023-05-25T21:02:15 [TRACE] - Wrote 92/92 bytes to 127.0.0.1:12378
components/client/src/session.rs:245 2023-05-25T21:02:15 [TRACE] - Write request[opcode=CreateRange] bounded for 127.0.0.1:12378 using stream-id=2 to socket buffer
components/transport/src/connection.rs:77 2023-05-25T21:02:15 [TRACE] - Read 172 bytes from 127.0.0.1:12378
components/codec/src/frame.rs:92 2023-05-25T21:02:15 [TRACE] - Incoming frame length is: 168
components/client/src/session.rs:109 2023-05-25T21:02:15 [TRACE] - Read a frame from channel=127.0.0.1:12378
components/client/src/session.rs:283 2023-05-25T21:02:15 [TRACE] - Received CreateRange response for stream-id=2
components/client/src/composite_session.rs:479 2023-05-25T21:02:15 [ERROR] - Failed to create range on localhost:12378 for elastic-stream[id=100]: Response {
    operation_code: CreateRange,
    status: Status {
        code: CREATE_RANGE_BEFORE_SEAL,
        message: "create range 0 before sealing the last range 0 in stream 100: create range before sealing the previous one",
        details: None,
    },
    headers: None,
    payload: None,
}
/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.6/src/poll.rs:663 2023-05-25T21:02:15 [TRACE] - deregistering event source from poller
Error: ServerInternal
test client::tests::test_create_range ... FAILED

failures:

failures:
    client::tests::test_create_range

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 15 filtered out; finished in 0.00s

**Comment by Chillax-0v0** [comment]
duplicate #300

**Comment by Chillax-0v0** [comment]
duplicate #300
