### ISSUE TITLE
Some improvements about the doc

### ISSUE THREAD

**Issue by wayne-2017** [AutoMQ/elastic-stream#624]
As I tried to build and launch the entire project, I've noticed that some sections of the README seem to be outdated. I would love to provide some improvements from a newcomer's perspective.

**Comment by lizhanhui** [comment]
@wayne-2017 Thanks for raising this issue... we are currently working on it

**Comment by wayne-2017** [comment]
Thank you! I will create a PR to follow up on this issue.
