### ISSUE TITLE
Reloading with different configuration may cause some trouble

### ISSUE THREAD

**Issue by Tianpingan** [AutoMQ/elastic-stream#646]
Reloading with different configurations (different segment file size, different total size, etc.) can lead to runtime errors, conflicts, or unexpected behavior.

**Comment by Tianpingan** [comment]
- different segment file size:
    - panic at the recovery stage
- different total size:
    -  larger than before
        - expand: allocate new segment files until the new limit is reached.
    -  less than before
        - shrink: delete the unused segment files and upload the used file to S3 until the new limit is reached.

**Comment by lizhanhui** [comment]
> panic at the recovery stage

We should have this pre-check
