### ISSUE TITLE
range_manager/range.rs committed meaning is confused

### ISSUE THREAD

**Issue by superhx** [AutoMQ/elastic-stream#906]
![image](https://github.com/AutoMQ/elastic-stream/assets/5719209/352d9b72-2547-4f98-bf58-e12091020416)

![image](https://github.com/AutoMQ/elastic-stream/assets/5719209/62b9bbc1-1b21-4439-9eb0-7a10b27304f1)

**Comment by lizhanhui** [comment]
Let's unify them, using the `end and inclusive` semantics.

**Comment by lizhanhui** [comment]
Given append result has included batch size and ack is always ordered,  we may remove the buffer map in `Window`
