### ISSUE TITLE
introduce tracing for uring main loop

### ISSUE THREAD

**Issue by ShadowySpirits** [AutoMQ/elastic-stream#913]
https://rustmagazine.github.io/rust_magazine_2021/chapter_2/rust_trace.html#local-span

I proposed to introduce minitrace. And I will only use LocalSpan and LocalCollector because the global collector will start some new threads without binding CPU.

https://github.com/tikv/minitrace-rust/blob/88c603369017733cc1e0c16defaa792c0a4bd910/minitrace/src/collector/global_collector.rs#L193-L212

Spans generated in the IO thread will be collected and sent to the trace thread via a channel. The trace thread which binds to CPU 0 will then report the spans to the opentelemetry collector.

**Comment by lizhanhui** [comment]
IO thread is running in the polling mode, which is similar to [PMD](https://doc.dpdk.org/guides/prog_guide/poll_mode_drv.html) of DPDK/SPDK, so every millisecond matters. Make sure the tracing introduces trivial overhead.

When communicating through threads, make sure to use a mechanism similar to a ring buffer.  Wait-and-notify is kind of slow;

Another key point is, receiving I/O tasks from the ring buffer may block if there are no inflight I/O jobs in the uring instance.
Remember to exclude the awaiting duration.
