### ISSUE TITLE
Improve the long tail latency resulting from uring::receive_io_tasks

### ISSUE THREAD

**Issue by ShadowySpirits** [AutoMQ/elastic-stream#923]
<img width="1251" alt="image" src="https://github.com/AutoMQ/elastic-stream/assets/32436597/743675f8-2dcd-403f-8ea7-b9dae1b03551">

**Comment by lizhanhui** [comment]
Receiving io-tasks is potentially blocking, awaiting incoming I/O tasks. It may not be an issue

**Comment by ShadowySpirits** [comment]
Update: After adding a flag to detect if the IO loop is trapped in blocking, I noticed that the crossbeam channel may cause a context switch to occur.

<img width="2536" alt="image" src="https://github.com/AutoMQ/elastic-stream/assets/32436597/5f3a2faf-d814-41c9-a398-480980f7dd25">

The context switch happened in some race conditions. The crossbeam channel uses `pause` instruction which has a risk of potential context switching.

![img_v2_93bdf5d4-7cd1-4a42-86f8-fcb4708d6b5g](https://github.com/AutoMQ/elastic-stream/assets/32436597/9da69708-de48-496d-a3cb-35e3073777b2)

I will try to replace the channel with spdk ring to verify the issue.

cc @lizhanhui @daniel-y

**Comment by ShadowySpirits** [comment]
To confirm the issue, I replaced the crossbeam channel with a non-blocking channel. Tracing shows that the longest duration of the io loop is now 275us, which is significantly improved from before.

![933ae2b7-3e71-419c-8fb1-ded475faa4d0](https://github.com/AutoMQ/elastic-stream/assets/32436597/c966b2bc-2a89-4fbb-9c1b-576b9fc45739)
